version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ChangeME!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - comonet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - comonet

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - comonet
    labels:
      traefik.enable: true
      traefik.docker.network: "comonet"
      traefik.http.routers.wordpress.entrypoints: "websecure"
      traefik.http.routers.wordpress.rule: "Host(`example.com`)"
      traefik.http.routers.wordpress.service: "wordpress-wordpress"

volumes:
  mysql_data:

networks:
  comonet:
    external: true
    name: comonet
